*Scala Language Updates*
regis-leray/fs2-ftp pull request #132
Opened 2021-04-29 14:27 UTC by rehanone

- Updated `scala-2.13 ` from 2.13.1 to 2.13.5

*Dependencies Updates*
- Updated `fs2` dependency from 2.5.0 to 3.0.2
- Updated `scala-collection-compat` dependency from 2.3.2 to 2.4.3
- Updated `commons-net` dependency from 3.7.2 to 3.8.0

*Plugin Updates*
- Updated `sbt-scoverage` plugin from 1.6.1 to 1.7.0
- Updated `sbt-sonatype` plugin from 3.9.5 to 3.9.7

2021-04-29 14:44 UTC, regis-leray commented on src/main/scala/fs2/ftp/UnsecureFtp.scala
> +    Sync[F].delay(f(unsafeClient))
Sync[F].delay is not equivalent to blocker.delay

please use `Sync[F].blocking()`

2021-04-29 14:46 UTC, regis-leray requested changes
great thank you :)

2021-04-29 15:04 UTC, rehanone commented
@regis-leray , Fixed the Sync[F].blocking. Their is one readFile test failing which I am not sure why. Any insight on that would be much helpful. Thanks!

2021-04-29 16:03 UTC, regis-leray commented
@rehanone thank you maybe a bug in fs2 ? try to open a bug 
i found a reference to this problem
https://github.com/typelevel/fs2/pull/1161#discussion_r195890105

```
[info]   java.lang.ClassCastException: class [Ljava.lang.Object; cannot be cast to class [B ([Ljava.lang.Object; and [B are in module java.base of loader 'bootstrap')
[info]   at fs2.Chunk.toByteBuffer(Chunk.scala:327)
```

2021-05-14 12:48 UTC, regis-leray commented
@rehanone please try new release https://github.com/typelevel/fs2/releases/tag/v3.0.3
it should work now.
thank you

2021-05-14 13:42 UTC, rehanone commented
@regis-leray , I have updated the PR, please review. Thanks.

2021-05-14 14:09 UTC, regis-leray approved these changes

2021-05-14 14:49 UTC, merged